// Try Catch:- Error Handling

let a = 10;
console.log(a / b);
try {
    
} catch (error) {
    
}